spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
  server:
   port: 8090
  servlet:
    context-path: /books-app

    logging:
        level:
          org.hibernate.SQL: debug
          org.springframework.web: info